[project]
name = "grobid-footnote-flavour"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipython>=8.37.0",
    "requests>=2.32.4",
    "tqdm>=4.67.1",
]
